name: my_first_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  pocketbase: ^0.7.1+1
  get: ^4.6.5
  cupertino_icons: ^1.0.5
  flutter_screenutil: ^5.6.1
  google_fonts: ^4.0.1
  get_cli: ^0.2.30
  dio: ^4.0.6
  flutter_svg: ^1.1.6
  cached_network_image: ^3.2.3
  flutter_svg_provider: ^1.0.3
  email_validator: ^2.1.17
  badges: ^3.0.2
  flutter_launcher_icons: ^0.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/daim_logo.png"
  remove_alpha_ios: true


flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/